events{}

http {
    include /etc/nginx/mime.types;

    server {
        root /usr/share/nginx/html;

        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /assets/ {
          expires 1d;
          add_header Cache-Control "public, max-age=86400";
          add_header Pragma "public";
          add_header Vary "Accept-Encoding";
          try_files $uri $uri/ /index.html;
        }

        location /mooncode-api/ {
          proxy_pass https://mooncode.loty.click/api/;
          proxy_ssl_server_name on;
          proxy_set_header Host mooncode.loty.click;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
