export const OFFICIAL_GAME_VISUAL_CONFIG = Object.freeze({
  tableScale: 1,
  centerScale: 1,
  centerOffsetX: 0,
  centerOffsetY: 0,
  seatScale: 1,
  seatOrbitX: 36,
  seatOrbitY: 28,
  seatLift: 2,
  bidControlScale: 1,
  bidControlOffsetX: 0,
  bidControlOffsetY: 0,
  powerDeckControlScale: 1,
  powerDeckControlOffsetX: 0,
  powerDeckControlOffsetY: 0,
  classicHandScale: 1,
  classicHandOffsetY: 0,
  powerHandScale: 1,
  powerHandOffsetX: 0,
  powerHandOffsetY: 0,
  animationDuration: 520,
  animationDelay: 180,
});
